### ISSUE TITLE
Have you reproduced experimental results of original paper

### ISSUE THREAD

**Issue by leroylight** [Dorian25/colorization-transformer-experimental#2]
Hi, have you trained models on imagenet with your reproduced codes? Can you release trained weights?? Or have you reproduced experimental results of original paper?

**Comment by Dorian25** [comment]
Hello, first of all thank you for your interest in our implementation ! 

Unfortunately, we could not train the model with real images (ImageNet) as in the paper... We didn't have the right equipment (powerful enough computers etc...) and had a limited time to make this project...
We just tried to run the training with random noisy images (toy dataset) of very small sizes of 8x8 and 4x4...

**Comment by pchankh** [comment]
Dorian, good work in the implementation! Perhaps we can try to train in colab and kaggle environment. Are there any scripts to train the models? Thks.

**Comment by Dorian25** [comment]
> Dorian, good work in the implementation! Perhaps we can try to train in colab and kaggle environment. Are there any scripts to train the models? Thks.

Thx mate ! 
We started the implementation via Colab ! But unfortunately, when we started training the first module, Colab's Ram reached its limit and stopped the process...

For the training, everything is in the [Main.py](https://github.com/Dorian25/colorization-transformer-experimental/blob/main/Main.py) file where you can choose to train the 3 modules  (core, color and spatial) separately or one at a time using the booleans *train_core*, *train_color* and *train_spatial*...
